import { InventoryItem, InventoryTransaction } from '@/types/inventory';

export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'INV-001',
    partName: 'Front Brake Pads',
    partNumber: 'BP-F-2024',
    category: 'Brakes',
    condition: 'Good',
    quantity: 2,
    unitPrice: 75000,
    totalValue: 150000,
    removedFromVehicle: 'UBJ 245T',
    removalDate: '2024-12-15T10:30:00',
    removalReason: 'Preventive Maintenance - 50% wear',
    storageLocation: 'Shelf A-12',
    status: 'In Storage',
    addedBy: 'John Mechanic',
    notes: 'Still functional, can be resold or reused',
  },
  {
    id: 'INV-002',
    partName: 'Alternator',
    partNumber: 'ALT-12V-150A',
    category: 'Electrical',
    condition: 'Fair',
    quantity: 1,
    unitPrice: 450000,
    totalValue: 450000,
    removedFromVehicle: 'UBE 123X',
    removalDate: '2024-12-18T14:20:00',
    removalReason: 'Replacement - New alternator installed',
    storageLocation: 'Shelf C-05',
    status: 'In Storage',
    addedBy: 'David Technician',
    notes: 'Tested - Output voltage slightly low but functional',
  },
  {
    id: 'INV-003',
    partName: 'Air Filter',
    partNumber: 'AF-HD-2024',
    category: 'Filters',
    condition: 'Poor',
    quantity: 4,
    unitPrice: 25000,
    totalValue: 100000,
    removedFromVehicle: 'UBJ 567K',
    removalDate: '2024-12-10T09:15:00',
    removalReason: 'Scheduled replacement',
    storageLocation: 'Bin D-22',
    status: 'Disposed',
    addedBy: 'Michael Service',
    notes: 'Too dirty to reuse - disposed via recycling',
  },
  {
    id: 'INV-004',
    partName: 'Radiator',
    partNumber: 'RAD-HD-2023',
    category: 'Cooling',
    condition: 'Good',
    quantity: 1,
    unitPrice: 350000,
    totalValue: 350000,
    removedFromVehicle: 'UAM 890P',
    removalDate: '2024-12-12T11:45:00',
    removalReason: 'Upgrade to new model',
    storageLocation: 'Shelf B-08',
    status: 'Sold',
    addedBy: 'Peter Workshop',
    notes: 'Sold to local mechanic shop for UGX 280,000',
  },
  {
    id: 'INV-005',
    partName: 'Shock Absorbers (Set of 4)',
    partNumber: 'SA-F-HD-2024',
    category: 'Suspension',
    condition: 'Good',
    quantity: 4,
    unitPrice: 120000,
    totalValue: 480000,
    removedFromVehicle: 'UBJ 245T',
    removalDate: '2024-12-20T08:30:00',
    removalReason: 'Preventive replacement at 100,000 km',
    storageLocation: 'Shelf A-15',
    status: 'In Storage',
    addedBy: 'John Mechanic',
    notes: 'Minimal wear, can be reused on lighter vehicles',
  },
  {
    id: 'INV-006',
    partName: 'Battery',
    partNumber: 'BAT-12V-100AH',
    category: 'Electrical',
    condition: 'Fair',
    quantity: 1,
    unitPrice: 380000,
    totalValue: 380000,
    removedFromVehicle: 'UBE 456M',
    removalDate: '2024-12-19T16:00:00',
    removalReason: 'Weak charging, replaced',
    storageLocation: 'Shelf C-10',
    status: 'In Storage',
    addedBy: 'David Technician',
    notes: 'Holds charge but reduced capacity, suitable for backup',
  },
  {
    id: 'INV-007',
    partName: 'Side Mirror (Right)',
    partNumber: 'MIR-R-HD',
    category: 'Body Parts',
    condition: 'Damaged',
    quantity: 1,
    unitPrice: 85000,
    totalValue: 85000,
    removedFromVehicle: 'UAM 234N',
    removalDate: '2024-12-08T13:20:00',
    removalReason: 'Accident damage',
    storageLocation: 'Bin E-05',
    status: 'Disposed',
    addedBy: 'Robert Manager',
    notes: 'Glass broken, frame bent - scrapped',
  },
];

export const MOCK_INVENTORY_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'TXN-001',
    inventoryItemId: 'INV-001',
    partName: 'Front Brake Pads',
    partNumber: 'BP-F-2024',
    transactionType: 'Added',
    quantity: 2,
    fromLocation: 'UBJ 245T',
    toLocation: 'Shelf A-12',
    transactionDate: '2024-12-15T10:30:00',
    performedBy: 'John Mechanic',
    notes: 'Removed during preventive maintenance',
  },
  {
    id: 'TXN-002',
    inventoryItemId: 'INV-004',
    partName: 'Radiator',
    partNumber: 'RAD-HD-2023',
    transactionType: 'Sold',
    quantity: 1,
    fromLocation: 'Shelf B-08',
    saleAmount: 280000,
    transactionDate: '2024-12-17T15:00:00',
    performedBy: 'Sarah Sales',
    notes: 'Sold to ABC Mechanic Shop',
  },
  {
    id: 'TXN-003',
    inventoryItemId: 'INV-003',
    partName: 'Air Filter',
    partNumber: 'AF-HD-2024',
    transactionType: 'Disposed',
    quantity: 4,
    fromLocation: 'Bin D-22',
    disposalMethod: 'Recycled',
    disposalReason: 'End of life - too dirty to reuse',
    transactionDate: '2024-12-11T10:00:00',
    performedBy: 'Michael Service',
    notes: 'Sent to recycling center',
  },
  {
    id: 'TXN-004',
    inventoryItemId: 'INV-007',
    partName: 'Side Mirror (Right)',
    partNumber: 'MIR-R-HD',
    transactionType: 'Disposed',
    quantity: 1,
    fromLocation: 'Bin E-05',
    disposalMethod: 'Scrapped',
    disposalReason: 'Damaged beyond repair',
    transactionDate: '2024-12-09T11:30:00',
    performedBy: 'Robert Manager',
    notes: 'Mirror glass broken, frame bent',
  },
  {
    id: 'TXN-005',
    inventoryItemId: 'INV-002',
    partName: 'Alternator',
    partNumber: 'ALT-12V-150A',
    transactionType: 'Added',
    quantity: 1,
    fromLocation: 'UBE 123X',
    toLocation: 'Shelf C-05',
    transactionDate: '2024-12-18T14:20:00',
    performedBy: 'David Technician',
    notes: 'Removed and replaced with new unit',
  },
];

export const PART_CATEGORIES = [
  'Brakes',
  'Electrical',
  'Filters',
  'Cooling',
  'Suspension',
  'Engine',
  'Transmission',
  'Body Parts',
  'Tires',
  'Lights',
  'Interior',
  'Other',
];

export const STORAGE_LOCATIONS = [
  'Shelf A-12',
  'Shelf A-15',
  'Shelf B-08',
  'Shelf C-05',
  'Shelf C-10',
  'Bin D-22',
  'Bin E-05',
  'Warehouse Section 1',
  'Warehouse Section 2',
  'Spare Room',
];
