import { Asset, LowStockAlert } from '@/types/asset';

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'AST-001',
    name: 'Front Brake Pads (HD)',
    type: 'Spare Part',
    sku: 'BP-F-HD-2024',
    description: 'Heavy duty front brake pads for commercial trucks',
    tracking: 'Batch',
    inStock: 24,
    assigned: 8,
    conditionMix: [
      { condition: 'New', count: 20 },
      { condition: 'Good', count: 4 },
    ],
    reorderLevel: 10,
    unitPrice: 75000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Warehouse A - Shelf 12',
    supplier: 'AutoParts Uganda Ltd',
    lastRestocked: '2026-01-15T10:30:00',
    createdAt: '2025-06-01T08:00:00',
    updatedAt: '2026-01-15T10:30:00',
  },
  {
    id: 'AST-002',
    name: 'Engine Oil Filter',
    type: 'Consumable',
    sku: 'OF-ENG-2024',
    description: 'Premium engine oil filter for diesel engines',
    tracking: 'FIFO',
    inStock: 45,
    assigned: 12,
    conditionMix: [
      { condition: 'New', count: 45 },
    ],
    reorderLevel: 20,
    unitPrice: 35000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Warehouse A - Bin 5',
    supplier: 'FilterMax East Africa',
    lastRestocked: '2026-01-20T14:00:00',
    createdAt: '2025-03-15T09:00:00',
    updatedAt: '2026-01-20T14:00:00',
  },
  {
    id: 'AST-003',
    name: 'Alternator 12V 150A',
    type: 'Spare Part',
    sku: 'ALT-12V-150A',
    description: 'High capacity alternator for heavy commercial vehicles',
    tracking: 'Serial Number',
    inStock: 5,
    assigned: 2,
    conditionMix: [
      { condition: 'New', count: 3 },
      { condition: 'Good', count: 2 },
    ],
    reorderLevel: 8,
    unitPrice: 450000,
    status: 'Available',
    stockStatus: 'Low Stock',
    location: 'Warehouse B - Shelf 3',
    supplier: 'Electrical Parts Co.',
    lastRestocked: '2025-12-10T11:30:00',
    createdAt: '2025-02-20T10:00:00',
    updatedAt: '2025-12-10T11:30:00',
  },
  {
    id: 'AST-004',
    name: 'Hydraulic Jack 10T',
    type: 'Tool',
    sku: 'HJ-10T-PRO',
    description: 'Professional grade 10-ton hydraulic floor jack',
    tracking: 'Serial Number',
    inStock: 8,
    assigned: 6,
    conditionMix: [
      { condition: 'New', count: 2 },
      { condition: 'Good', count: 4 },
      { condition: 'Fair', count: 2 },
    ],
    reorderLevel: 4,
    unitPrice: 850000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Tool Room - Bay 2',
    supplier: 'Industrial Tools Uganda',
    lastRestocked: '2025-11-05T09:00:00',
    createdAt: '2024-08-15T08:00:00',
    updatedAt: '2025-11-05T09:00:00',
  },
  {
    id: 'AST-005',
    name: 'Radiator Coolant 5L',
    type: 'Consumable',
    sku: 'RC-5L-HD',
    description: 'Heavy duty radiator coolant concentrate',
    tracking: 'FIFO',
    inStock: 3,
    assigned: 0,
    conditionMix: [
      { condition: 'New', count: 3 },
    ],
    reorderLevel: 15,
    unitPrice: 65000,
    status: 'Available',
    stockStatus: 'Low Stock',
    location: 'Warehouse A - Shelf 8',
    supplier: 'Lubricants Plus',
    lastRestocked: '2025-12-28T16:00:00',
    createdAt: '2025-01-10T08:00:00',
    updatedAt: '2025-12-28T16:00:00',
  },
  {
    id: 'AST-006',
    name: 'Diagnostic Scanner Pro',
    type: 'Equipment',
    sku: 'DS-PRO-2025',
    description: 'Professional OBD-II diagnostic scanner with advanced features',
    tracking: 'Serial Number',
    inStock: 4,
    assigned: 3,
    conditionMix: [
      { condition: 'New', count: 1 },
      { condition: 'Good', count: 3 },
    ],
    reorderLevel: 2,
    unitPrice: 2500000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Tool Room - Cabinet 1',
    supplier: 'TechDiag East Africa',
    lastRestocked: '2025-10-15T10:00:00',
    createdAt: '2025-05-20T08:00:00',
    updatedAt: '2025-10-15T10:00:00',
  },
  {
    id: 'AST-007',
    name: 'Air Filter Heavy Duty',
    type: 'Spare Part',
    sku: 'AF-HD-2024',
    description: 'Heavy duty air filter for diesel trucks',
    tracking: 'Batch',
    inStock: 0,
    assigned: 0,
    conditionMix: [],
    reorderLevel: 12,
    unitPrice: 45000,
    status: 'Available',
    stockStatus: 'Out of Stock',
    location: 'Warehouse A - Bin 12',
    supplier: 'FilterMax East Africa',
    lastRestocked: '2025-11-20T14:00:00',
    createdAt: '2025-04-01T08:00:00',
    updatedAt: '2026-01-25T09:00:00',
  },
  {
    id: 'AST-008',
    name: 'Shock Absorber Set (Front)',
    type: 'Spare Part',
    sku: 'SA-F-HD-2024',
    description: 'Front shock absorber set for heavy duty trucks',
    tracking: 'Serial Number',
    inStock: 12,
    assigned: 4,
    conditionMix: [
      { condition: 'New', count: 8 },
      { condition: 'Good', count: 3 },
      { condition: 'Fair', count: 1 },
    ],
    reorderLevel: 6,
    unitPrice: 280000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Warehouse B - Shelf 7',
    supplier: 'Suspension Systems Ltd',
    lastRestocked: '2026-01-08T11:00:00',
    createdAt: '2025-07-15T08:00:00',
    updatedAt: '2026-01-08T11:00:00',
  },
  {
    id: 'AST-009',
    name: 'Battery 12V 100AH',
    type: 'Spare Part',
    sku: 'BAT-12V-100AH',
    description: 'Heavy duty truck battery with 100AH capacity',
    tracking: 'Serial Number',
    inStock: 7,
    assigned: 2,
    conditionMix: [
      { condition: 'New', count: 5 },
      { condition: 'Good', count: 2 },
    ],
    reorderLevel: 5,
    unitPrice: 380000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Warehouse B - Shelf 1',
    supplier: 'PowerCell Uganda',
    lastRestocked: '2026-01-12T09:30:00',
    createdAt: '2025-02-01T08:00:00',
    updatedAt: '2026-01-12T09:30:00',
  },
  {
    id: 'AST-010',
    name: 'LED Work Light 48W',
    type: 'Accessory',
    sku: 'LED-WL-48W',
    description: '48W LED work light for trucks and workshops',
    tracking: 'Batch',
    inStock: 18,
    assigned: 10,
    conditionMix: [
      { condition: 'New', count: 12 },
      { condition: 'Good', count: 6 },
    ],
    reorderLevel: 8,
    unitPrice: 95000,
    status: 'Available',
    stockStatus: 'In Stock',
    location: 'Warehouse A - Shelf 15',
    supplier: 'Lighting Solutions EA',
    lastRestocked: '2026-01-18T14:00:00',
    createdAt: '2025-09-10T08:00:00',
    updatedAt: '2026-01-18T14:00:00',
  },
];

export const MOCK_LOW_STOCK_ALERTS: LowStockAlert[] = [
  {
    assetId: 'AST-003',
    assetName: 'Alternator 12V 150A',
    currentStock: 5,
    reorderLevel: 8,
    deficit: 3,
  },
  {
    assetId: 'AST-005',
    assetName: 'Radiator Coolant 5L',
    currentStock: 3,
    reorderLevel: 15,
    deficit: 12,
  },
  {
    assetId: 'AST-007',
    assetName: 'Air Filter Heavy Duty',
    currentStock: 0,
    reorderLevel: 12,
    deficit: 12,
  },
];

export const ASSET_TYPE_OPTIONS = [
  { value: 'all', label: 'All Types' },
  { value: 'Spare Part', label: 'Spare Part' },
  { value: 'Tool', label: 'Tool' },
  { value: 'Equipment', label: 'Equipment' },
  { value: 'Consumable', label: 'Consumable' },
  { value: 'Accessory', label: 'Accessory' },
];

export const STOCK_STATUS_OPTIONS = [
  { value: 'all', label: 'All Stock Status' },
  { value: 'In Stock', label: 'In Stock' },
  { value: 'Low Stock', label: 'Low Stock' },
  { value: 'Out of Stock', label: 'Out of Stock' },
  { value: 'Overstocked', label: 'Overstocked' },
];

export const CONDITION_OPTIONS = [
  { value: 'all', label: 'All Conditions' },
  { value: 'New', label: 'New' },
  { value: 'Good', label: 'Good' },
  { value: 'Fair', label: 'Fair' },
  { value: 'Poor', label: 'Poor' },
  { value: 'Damaged', label: 'Damaged' },
];
