import { MaintenanceDashboardData, WorkOrder } from '@/types/maintenance';

export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'WO-2023-001',
    vehicleId: 'v1',
    vehiclePlate: 'KBX-234T',
    vehicleModel: 'Toyota HiAce',
    type: 'corrective',
    status: 'in-progress',
    priority: 'high',
    category: 'engine',
    description: 'Engine overheating and unusual noise during acceleration',
    reportedBy: 'John Doe (Driver)',
    assignedTo: 'Mike Mechanic',
    startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    parts: [
      { id: 'p1', name: 'Radiator Hose', quantity: 1, unitCost: 1500, totalCost: 1500 },
      { id: 'p2', name: 'Coolant (5L)', quantity: 2, unitCost: 800, totalCost: 1600 },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'WO-2023-002',
    vehicleId: 'v2',
    vehiclePlate: 'KCA-567M',
    vehicleModel: 'Isuzu FRR',
    type: 'preventive',
    status: 'completed',
    priority: 'medium',
    category: 'fluids',
    description: 'Scheduled oil change and filter replacement',
    reportedBy: 'System Schedule',
    assignedTo: 'Jane Smith',
    startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    completedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    cost: 15000,
    parts: [
      { id: 'p3', name: 'Oil Filter', quantity: 1, unitCost: 2500, totalCost: 2500 },
      { id: 'p4', name: 'Engine Oil (20L)', quantity: 1, unitCost: 8500, totalCost: 8500 },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'WO-2023-003',
    vehicleId: 'v3',
    vehiclePlate: 'KBZ-890P',
    vehicleModel: 'Mitsubishi Fuso',
    type: 'inspection',
    status: 'pending',
    priority: 'low',
    category: 'inspection',
    description: 'Quarterly safety inspection',
    reportedBy: 'System Schedule',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'WO-2023-004',
    vehicleId: 'v4',
    vehiclePlate: 'KDD-123L',
    vehicleModel: 'Toyota Land Cruiser',
    type: 'emergency',
    status: 'awaiting-parts',
    priority: 'critical',
    category: 'brakes',
    description: 'Brake failure on rear left wheel',
    reportedBy: 'Driver James',
    assignedTo: 'Mike Mechanic',
    startDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    notes: 'Waiting for brake pads shipment',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'WO-2023-005',
    vehicleId: 'v5',
    vehiclePlate: 'KBA-111A',
    vehicleModel: 'Nissan Urvan',
    type: 'corrective',
    status: 'cancelled',
    priority: 'low',
    category: 'body-paint',
    description: 'Minor scratch on side door',
    reportedBy: 'Fleet Manager',
    dueDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    notes: 'Deemed cosmetic only, will address later',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
];

// Mock data for the maintenance dashboard
export const mockMaintenanceDashboard: MaintenanceDashboardData = {
  stats: {
    totalActiveWorkOrders: 24,
    vehiclesOverdue: 7,
    scheduledThisWeek: 12,
    vehiclesInWorkshop: 5,
    averageDowntimeDays: 2.3,
    monthlyCost: 145780,
    partsInventoryAlerts: 3,
  },
  alerts: [
    {
      id: '1',
      type: 'overdue',
      severity: 'critical',
      message: '3 vehicles have overdue preventive maintenance',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: '2',
      type: 'breakdown',
      severity: 'critical',
      message: 'Vehicle KBX-234T reported breakdown - Engine issue',
      vehicleId: 'v1',
      workOrderId: 'wo1',
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    {
      id: '3',
      type: 'parts',
      severity: 'warning',
      message: 'Low stock: Brake pads (3 units remaining)',
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    {
      id: '4',
      type: 'due-soon',
      severity: 'warning',
      message: '4 vehicles due for service within 7 days',
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      id: '5',
      type: 'warranty',
      severity: 'info',
      message: 'Warranty expiring for 2 vehicles this month',
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
  ],
  vehicleStatus: {
    operational: 82,
    dueForService: 15,
    inWorkshop: 5,
    outOfService: 3,
  },
  workOrderStatus: {
    pending: 8,
    inProgress: 11,
    awaitingParts: 5,
    completed: 156,
    cancelled: 3,
  },
  maintenanceDistribution: {
    preventive: 45,
    corrective: 30,
    emergency: 12,
    inspection: 10,
    recall: 3,
  },
  recentActivity: [
    {
      id: '1',
      type: 'breakdown-reported',
      message: 'Emergency breakdown reported',
      vehicleId: 'v1',
      vehiclePlate: 'KBX-234T',
      timestamp: new Date(Date.now() - 30 * 60 * 1000),
      workOrderId: 'wo1',
    },
    {
      id: '2',
      type: 'work-order-completed',
      message: 'Oil change and filter replacement completed',
      vehicleId: 'v2',
      vehiclePlate: 'KCA-567M',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      workOrderId: 'wo2',
    },
    {
      id: '3',
      type: 'service-started',
      message: 'Brake system overhaul started',
      vehicleId: 'v3',
      vehiclePlate: 'KBZ-890P',
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      workOrderId: 'wo3',
    },
    {
      id: '4',
      type: 'work-order-created',
      message: 'Preventive maintenance scheduled',
      vehicleId: 'v4',
      vehiclePlate: 'KCB-123H',
      timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      workOrderId: 'wo4',
    },
    {
      id: '5',
      type: 'work-order-completed',
      message: 'Tyre rotation and alignment completed',
      vehicleId: 'v5',
      vehiclePlate: 'KBY-456L',
      timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
      workOrderId: 'wo5',
    },
  ],
};
