import { Route } from '@/types/route';

export const MOCK_ROUTES: Route[] = [
  {
    id: '1',
    name: 'Morning Delivery - Sector A',
    startLocation: 'Central Warehouse',
    endLocation: 'Downtown Distribution Center',
    distance: '15.4 km',
    estimatedDuration: '45 mins',
    status: 'In Progress',
    date: '2025-12-13',
  },
  {
    id: '2',
    name: 'Afternoon Pickup - Sector B',
    startLocation: 'North Industrial Park',
    endLocation: 'Central Warehouse',
    distance: '22.1 km',
    estimatedDuration: '55 mins',
    status: 'Scheduled',
    date: '2025-12-13',
  },
  {
    id: '3',
    name: 'Express Delivery - Client X',
    startLocation: 'Central Warehouse',
    endLocation: 'Tech Park, Building 4',
    distance: '8.5 km',
    estimatedDuration: '20 mins',
    status: 'Completed',
    date: '2025-12-12',
  },
  {
    id: '4',
    name: 'Night Haul - Intercity',
    startLocation: 'City A Hub',
    endLocation: 'City B Hub',
    distance: '145 km',
    estimatedDuration: '2h 30m',
    status: 'Scheduled',
    date: '2025-12-14',
  },
  {
    id: '5',
    name: 'Maintenance Run',
    startLocation: 'Garage',
    endLocation: 'Testing Facility',
    distance: '5 km',
    estimatedDuration: '15 mins',
    status: 'Cancelled',
    date: '2025-12-11',
  },
];
