import { Truck } from '@/types/truck';

export const MOCK_TRUCKS: Truck[] = [
  {
    id: 'truck-1',
    plateNumber: 'KBA 123A',
    make: 'Isuzu',
    model: 'FRR',
    year: 2022,
    vinNumber: 'JL5PJAZ8D5G215903',
    color: 'White',
    axleConfig: '2 Steer, 2 Drive',
    currentOdometer: 125430,
    engineHours: 4500,
    fuelType: 'Diesel',
    fuelTankCapacity: 150,
    engineNumber: 'ENG-2022-001',
    engineCapacity: 5200,
    transmissionType: 'Manual',
    driver: {
      id: 'd1',
      name: 'John Karanja',
      licenseNumber: 'DL1234567',
    },
    status: 'Active',
    alerts: 2,
    assignedTyres: 6,
  },
  {
    id: 'truck-2',
    plateNumber: 'KBC 456B',
    make: 'Scania',
    model: 'R450',
    year: 2021,
    vinNumber: 'JL5PJAZ8D5G215904',
    color: 'Blue',
    axleConfig: '2 Steer, 2 Drive, 1 Lift',
    currentOdometer: 156780,
    engineHours: 5200,
    fuelType: 'Diesel',
    fuelTankCapacity: 200,
    engineNumber: 'ENG-2021-002',
    engineCapacity: 5600,
    transmissionType: 'Manual',
    driver: {
      id: 'd2',
      name: 'Peter Kipchoge',
      licenseNumber: 'DL2345678',
    },
    status: 'Active',
    alerts: 0,
    assignedTyres: 10,
  },
  {
    id: 'truck-3',
    plateNumber: 'KBD 789C',
    make: 'Mercedes-Benz',
    model: 'Sprinter',
    year: 2023,
    vinNumber: 'JL5PJAZ8D5G215905',
    color: 'White',
    axleConfig: '2 Steer, 2 Drive',
    currentOdometer: 98458,
    engineHours: 3200,
    fuelType: 'Diesel',
    fuelTankCapacity: 120,
    engineNumber: 'ENG-2023-003',
    engineCapacity: 3500,
    transmissionType: 'Automatic',
    driver: {
      id: 'd3',
      name: 'Samuel Kiplagat',
      licenseNumber: 'DL3456789',
    },
    status: 'Active',
    alerts: 1,
    assignedTyres: 6,
  },
  {
    id: 'truck-4',
    plateNumber: 'KBE 234D',
    make: 'Volvo',
    model: 'FM',
    year: 2020,
    vinNumber: 'JL5PJAZ8D5G215906',
    color: 'Red',
    axleConfig: '2 Steer, 2 Drive',
    currentOdometer: 189567,
    engineHours: 6700,
    fuelType: 'Diesel',
    fuelTankCapacity: 180,
    engineNumber: 'ENG-2020-004',
    engineCapacity: 5500,
    transmissionType: 'Manual',
    driver: {
      id: 'd4',
      name: 'James Mwangi',
      licenseNumber: 'DL4567890',
    },
    status: 'Maintenance',
    alerts: 3,
    assignedTyres: 8,
  },
  {
    id: 'truck-5',
    plateNumber: 'KBF 567E',
    make: 'MAN',
    model: 'TGX',
    year: 2022,
    vinNumber: 'JL5PJAZ8D5G215907',
    color: 'White',
    axleConfig: '2 Steer, 2 Drive, 1 Lift',
    currentOdometer: 134560,
    engineHours: 4800,
    fuelType: 'Diesel',
    fuelTankCapacity: 200,
    engineNumber: 'ENG-2022-005',
    engineCapacity: 5900,
    transmissionType: 'Manual',
    driver: null,
    status: 'Inactive',
    alerts: 5,
    assignedTyres: 0,
  },
  {
    id: 'truck-6',
    plateNumber: 'KBG 890F',
    make: 'Howo',
    model: 'A7',
    year: 2021,
    vinNumber: 'JL5PJAZ8D5G215908',
    color: 'Yellow',
    axleConfig: '2 Steer, 2 Drive',
    currentOdometer: 167890,
    engineHours: 5600,
    fuelType: 'Diesel',
    fuelTankCapacity: 150,
    engineNumber: 'ENG-2021-006',
    engineCapacity: 4900,
    transmissionType: 'Manual',
    driver: {
      id: 'd5',
      name: 'David Njoroge',
      licenseNumber: 'DL5678901',
    },
    status: 'Active',
    alerts: 0,
    assignedTyres: 6,
  },
];
